package com.kiotretail.controller;

import com.kiotretail.dao.EmployeeDAO;
import com.kiotretail.model.Employee;
import com.kiotretail.util.EmailUtil;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.io.IOException;

public class RegisterServlet extends HttpServlet {

    private EmployeeDAO employeeDAO;

    @Override
    public void init() throws ServletException {
        employeeDAO = new EmployeeDAO();
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        // --- CHẶN BẢO MẬT: Chỉ cho phép Owner mới truy cập vào trang này ---
        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("employee") == null) {
            response.sendRedirect(request.getContextPath() + "/login");
            return;
        }
        
        String roleName = (String) session.getAttribute("roleName");
        // Kiểm tra xem có đúng là chủ sở hữu chuỗi cửa hàng truy cập không
        if (!"owner".equalsIgnoreCase(roleName)) {
            response.sendError(HttpServletResponse.SC_FORBIDDEN, "Bạn không có quyền truy cập tính năng này.");
            return;
        }

        request.getRequestDispatcher("/WEB-INF/views/auth/register.jsp").forward(request, response);
    }

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        // Xác thực quyền lại tại cổng POST để tránh hacker gửi Request ngầm
        HttpSession session = request.getSession(false);
        if (session == null || !"owner".equalsIgnoreCase((String) session.getAttribute("roleName"))) {
            response.sendError(HttpServletResponse.SC_FORBIDDEN);
            return;
        }

        // Đọc dữ liệu từ form Owner nhập lên
        String fullName = request.getParameter("fullName");
        String email = request.getParameter("email");
        String phone = request.getParameter("phone");
        String roleIdStr = request.getParameter("roleId");
        String branchIdStr = request.getParameter("branchId");

        // 1. Kiểm tra Validate dữ liệu rỗng cơ bản
        if (fullName == null || fullName.trim().isEmpty() ||
            email == null || email.trim().isEmpty() ||
            phone == null || phone.trim().isEmpty() ||
            roleIdStr == null || branchIdStr == null) {
            
            request.setAttribute("error", "Vui lòng nhập và lựa chọn đầy đủ tất cả các trường dữ liệu!");
            request.getRequestDispatcher("/WEB-INF/views/auth/register.jsp").forward(request, response);
            return;
        }

        // Kiểm tra trùng lặp email trên hệ thống thông qua DAO của bạn
        if (employeeDAO.isEmailExists(email.trim())) {
            request.setAttribute("error", "Địa chỉ Email này đã tồn tại trên hệ thống!");
            request.getRequestDispatcher("/WEB-INF/views/auth/register.jsp").forward(request, response);
            return;
        }

        int roleId = Integer.parseInt(roleIdStr);
        int branchId = Integer.parseInt(branchIdStr);
        String defaultStatus = "active"; 

        // 2. Tiến hành tự động sinh mật khẩu ngẫu nhiên
        String autoGeneratedPassword = EmailUtil.generateRandomPassword();

        // 3. Gửi Email thông báo mật khẩu cho nhân viên
        boolean isMailSent = EmailUtil.sendPasswordEmail(email.trim(), fullName.trim(), autoGeneratedPassword);

        if (!isMailSent) {
            request.setAttribute("error", "Hệ thống không thể gửi email kích hoạt. Vui lòng kiểm tra lại cấu hình mạng mạng/email!");
            request.getRequestDispatcher("/WEB-INF/views/auth/register.jsp").forward(request, response);
            return;
        }

        // 4. Lưu dữ liệu xuống database
        // (Thời gian tạo hệ thống tự động lưu do trường CreatedAt trong DBFinora.sql đã có DEFAULT GETDATE())
        boolean isSuccess = employeeDAO.registerEmployee(
                fullName.trim(), email.trim(), phone.trim(), autoGeneratedPassword, roleId, branchId, defaultStatus
        );

        if (isSuccess) {
            request.setAttribute("successMessage", "Tài khoản nhân viên mới đã khởi tạo thành công và mật khẩu đã gửi tới hòm thư " + email);
            request.getRequestDispatcher("/WEB-INF/views/auth/register.jsp").forward(request, response);
        } else {
            request.setAttribute("error", "Đã xảy ra sự cố cơ sở dữ liệu khi lưu thông tin nhân viên.");
            request.getRequestDispatcher("/WEB-INF/views/auth/register.jsp").forward(request, response);
        }
    }
}